spring:
    application:
        name: generateUnitTestForMock
server:
  port: 80
generate:
  repository:
    path: execution(public * xxyy.unittest.generateunittestformock.service..*.*(..)))
  service:
    path: servicePath
  filepath: C:\Users\xxyyg\Desktop\unitTest.txt